SELECT * FROM tbproduct;


SELECT * FROM tbproduct;

SELECT * FROM tbproduct WHERE PRECO_LISTA BETWEEN 16.007 AND 16.009;
SELECT * FROM tbproduct WHERE PRECO_LISTA >= 16.007;
SELECT * FROM tbproduct WHERE PRECO_LISTA <= 16.009;

SELECT * FROM tbproduct WHERE  PRECO_LISTA >= 16.007 AND PRECO_LISTA <= 16.009;


SELECT * FROM tbclient WHERE (IDADE >= 18 AND IDADE <= 22 AND SEXO = 'M')
 OR (cidade = 'Rio de Janeiro' OR BAIRRO = 'Jardins');