SELECT * FROM tbclient;

SELECT * FROM tbclient WHERE IDADE = 22;

SELECT * FROM tbclient WHERE IDADE > 22;

SELECT * FROM tbclient WHERE IDADE < 22;

SELECT * FROM tbclient WHERE IDADE <= 22;

SELECT * FROM tbclient WHERE IDADE <> 22;

SELECT * FROM tbclient WHERE NOME >= 'Fernando Cavalcante';

SELECT * FROM tbclient WHERE NOME <> 'Fernando Cavalcante';

SELECT * FROM tbproduct;

SELECT * FROM tbproduct WHERE PRECO_LISTA > 16.008;

SELECT * FROM tbproduct WHERE PRECO_LISTA < 16.008;

SELECT * FROM tbproduct WHERE PRECO_LISTA <> 16.008;

SELECT * FROM tbproduct WHERE PRECO_LISTA BETWEEN 16.007 AND 16.009;